# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""MUSA toolkit configuration information.

This file is auto-generated by musa_configure.bzl.
"""

load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

def musa_config():
    return struct(
        gpu_architectures = %{musa_gpu_architectures},
        version = "%{musa_version}",
        version_number = %{musa_version_number},
        mcc_path = "%{mcc_path}",
        musa_path = "%{musa_path}",
        musa_root = "%{musa_root}",
        library_paths = %{musa_library_paths},
        musart_path = "%{musart_path}",
        mublas_path = "%{mublas_path}",
        mudnn_path = "%{mudnn_path}",
        musa_driver_path = "%{musa_driver_path}",
        mccl_path = "%{mccl_path}",
        cuda2musa_path = "%{cuda2musa_path}",
    )

def if_musa(if_true, if_false = []):
    return select({
        "@local_config_musa//musa:using_musa": if_true,
        "//conditions:default": if_false,
    })

def musa_default_copts():
    return if_musa([
        "-DTENSORFLOW_USE_MUSA=1",
        "-DMUSA_ENABLED=1",
        "-DUSE_MUSA=1",
    ])

def musa_library(copts = [], deps = [], **kwargs):
    cc_library(
        copts = musa_default_copts() + ["-x", "musa"] + copts,
        deps = deps + ["@local_config_musa//musa:musa_runtime"],
        **kwargs
    )

def musa_cc_test(copts = [], deps = [], **kwargs):
    cc_test(
        copts = copts + musa_default_copts(),
        deps = deps + ["@local_config_musa//musa:musa_runtime"],
        **kwargs
    )
